apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: osamaelgebaly/idtest:idtest_webapp
        ports:
        - name: webapp
          containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests-generator
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: requests-generator
  template:
    metadata:
      name: requests-generator
      labels:
        app: requests-generator
    spec:
      containers:
      - name: requests-generator
        image: osamaelgebaly/idtest:idtest_generator
        imagePullPolicy: Always
        