apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: monitoring
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: osamaelgebaly/idtest:idtest_webapp
      ports:
        - containerPort: 5000
      imagePullPolicy: IfNotPresent

    - name: requests-generator
      image: osamaelgebaly/idtest:idtest_generator
      imagePullPolicy: IfNotPresent
