apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: idtest_webapp
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
      - name: requests-generator
        image: idtest_generator
        imagePullPolicy: IfNotPresent
        