{
 "title": "webapp_DB Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of Requests / EP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[2m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Number Of Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[2m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Average response time ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[5m])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[2m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.25\"}[2m]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\"}[2m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total[2m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"flaskapp\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"flaskapp\"}[2m])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}